/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    ParamValue,
    RouteRecordInfo
  } from 'unplugin-vue-router/types';

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accounts-roles-permissions': RouteRecordInfo<'accounts-roles-permissions', '/accounts/roles-permissions', Record<never, never>, Record<never, never>>,
    'accounts-users': RouteRecordInfo<'accounts-users', '/accounts/Users', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'accounts-roles': RouteRecordInfo<'accounts-roles', '/accounts-roles', Record<never, never>, Record<never, never>>,
  }
}
